export const STRING_POOL = {
  SPACE: ' ',
  EMPTY: '',
  COMMA: ',',
  DOT: '.',
  COLON: ':',
  SEMICOLON: ';',
  SLASH: '/',
  BACKSLASH: '\\',
  UNDERSCORE: '_',
  HYPHEN: '-',
  PIPE: '|',
  PLUS: '+',
  MINUS: '-',
  PERCENT: '%',
  ASTERISK: '*',
  AMPERSAND: '&',
  CARET: '^',
  DOLLAR: '$',
  TILDE: '~',
  AT: '@',
  EXCLAMATION: '!',
  QUESTION: '?',
  HASH: '#',
  EQUAL: '=',
  APOSTROPHE: '\'',
  QUOTATION: '"',
  LEFT_PARENTHESIS: '(',
  RIGHT_PARENTHESIS: ')',
  LEFT_BRACKET: '[',
  RIGHT_BRACKET: ']',
}
